import { FutbinInnerStatsData } from '../types.js'

export const defaultInnerStatsData: FutbinInnerStatsData = {
  PACE: null,
  acceleration: null,
  sprintSpeed: null,
  SHOOTING: null,
  positioning: null,
  finishing: null,
  shotPower: null,
  longShots: null,
  volleys: null,
  penalties: null,
  PASSING: null,
  vision: null,
  crossing: null,
  freeKickAccuracy: null,
  shortPassing: null,
  longPassing: null,
  curve: null,
  DRIBBLING: null,
  agility: null,
  balance: null,
  reactions: null,
  ballControl: null,
  composure: null,
  DEFENDING: null,
  interceptions: null,
  headingAccuracy: null,
  standingTackle: null,
  slidingTackle: null,
  PHYSICALITY: null,
  jumping: null,
  stamina: null,
  strength: null,
  aggression: null,
}
